spring:
    application:
        name: libraryapi
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: postgres
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate.format_sql: true